// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/google/wire"
	"githubntf/app/proto"
	"githubntf/app/repository/gateway"
	"githubntf/app/repository/repo"
	"githubntf/app/repository/resolver"
	"githubntf/app/service"
	"githubntf/common/client"
	"githubntf/common/config"
)

// Injectors from container.go:

func NewRepoService() *resolver.Resolver {
	repoRepository := gateway.NewRepoGateway()
	configConfig := config.NewConfig()
	mongoRepository := repo.NewMongoRepository(configConfig)
	repoService := service.NewRepoService(repoRepository, mongoRepository)
	resolverResolver := resolver.NewResolver(repoService)
	return resolverResolver
}

func NewProtoService() *proto.Server {
	repoRepository := gateway.NewRepoGateway()
	configConfig := config.NewConfig()
	mongoRepository := repo.NewMongoRepository(configConfig)
	repoService := service.NewRepoService(repoRepository, mongoRepository)
	server := proto.NewProtoServer(repoService)
	return server
}

// container.go:

var InjectorSet = wire.NewSet(config.NewConfig, gateway.NewRepoGateway, repo.NewMongoRepository, service.NewRepoService, resolver.NewResolver, proto.NewProtoServer, client.NewRepositoryServiceClient)
