// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/google/wire"
	"githubntf/app/config"
	"githubntf/app/proto"
	"githubntf/app/repository/gateway"
	"githubntf/app/repository/repo"
	"githubntf/app/repository/resolver"
	"githubntf/app/service"
)

// Injectors from container.go:

func NewRepoService() *resolver.Resolver {
	repoRepository := gateway.NewRepoGateway()
	configConfig := config.NewConfig()
	repoMongoRepository := repo.NewMongoRepository(configConfig)
	repoService := service.NewRepoService(repoRepository, repoMongoRepository)
	resolverResolver := resolver.NewResolver(repoService)
	return resolverResolver
}

func NewProtoService() *proto.Server {
	repoRepository := gateway.NewRepoGateway()
	configConfig := config.NewConfig()
	repoMongoRepository := repo.NewMongoRepository(configConfig)
	repoService := service.NewRepoService(repoRepository, repoMongoRepository)
	server := proto.NewProtoServer(repoService)
	return server
}

// container.go:

var mongoRepository = repo.NewMongoRepository

var InjectorSet = wire.NewSet(config.NewConfig, gateway.NewRepoGateway, mongoRepository, service.NewRepoService, resolver.NewResolver, proto.NewProtoServer)
